### ISSUE TITLE
fyi similar projects

### ISSUE THREAD

**Issue by sDaniel** [travist/drupal.api.js#3]
You probably know about those projects but in case someone finds this (extremly promising!) project of yours he or she might be interested to know that there are other similar projects to look at. 
- http://drupal.org/project/drupalgap https://github.com/signalpoint/DrupalGap
- http://drupanium.org/
- http://drupal.org/project/phonegap 

In the long run I think it could make sense to share a comon drupal javascript core service and domain layer among such projects with plugable system for io. e.g. gui and specific hardware connection (database, mobile device) layers like one to work with jQuery mobile, PhoneGap or Titanium.

**Comment by travist** [comment]
Hey, thanks for the links!  I actually know very well about those projects.  The one BIG difference with this library vs. the others, is it was developed to be both object oriented and also platform independent.  I am currently using this for a PhoneGap application (which I will share my code when I am done), but it could easily be used for both Node.js as well as Titanium much like the drupanium project uses.  I think this model, however, it much more flexible in that it isn't tied to any platform.  I would love it if those projects would use this library as their Drupal JS layer, but that is a different issue in a different project.  :)

Thanks again for your links....

**Comment by sDaniel** [comment]
Thanks for the quick reply. 

Exactly the flexibility is why I think your project has a lot potential. :)

I'll dig into it more as soon as I find the time.
