### ISSUE TITLE
Services needs csrf token now

### ISSUE THREAD

**Issue by Gys** [travist/drupal.api.js#4]
Hi Travis

I do not see any support for the new csrf token (added in Services 3.4).
For some background and implementation ee https://drupal.org/node/2013781#comment-7507759
Any plans for adding that to your library ? Other then this I really would to use your library. I currently use my own custom library. Its simple and effective (and includes csrf) but I think it is not very structured. Your oo library might be the best alternative.

**Comment by travist** [comment]
Sorry for the long wait on this fix, but I just pushed up the 2.x version of this library now with support of the latest Services module.
