### ISSUE TITLE
Sample for creating node with fields?

### ISSUE THREAD

**Issue by giorgio79** [travist/drupal.api.js#7]
This js api rocks. Would love an example for a more complex node creation with fields.

**Comment by travist** [comment]
To create a node with fields, you simply need to add them to a `fields` parameter in the  JSON object like so...

```
(new drupal.node({
  title:"My new Node",
  fields: {
    field_a: {
      value: 'My field value.'
    },
    field_b: {
     value: 'My field value.'
    }
  }
})).save();
```

I added this fairly recently so it should work.  https://github.com/travist/drupal.api.js/commit/6b7037e04531fe643a4767c63ac395c62e705292

**Comment by travist** [comment]
Updated the README.

**Comment by giorgio79** [comment]
Fantastic thx. I notice the "und" is hardcoded, but multilingual sites would need to be able to change this. Might as well let the users set it like here https://www.drupal.org/project/drupalservicejs
