### ISSUE TITLE
Handling errors on node creation (eg failed validation)

### ISSUE THREAD

**Issue by giorgio79** [travist/drupal.api.js#8]
Hello,

I wonder how I could access the error message from the server that is sent back during node creation for example (eg the node failed validation).

For example

```
  (new drupal.node({title:"",type:"page"})).save(function(node) {
    console.log(node);
    //console.log(xhr.statusText);
  });
```

This call will fail of course as title is empty. It seems we only get a console.log from the API, but I want to show xhr.responseText to the user that contains the entire server message. How can I get the error message sent back from the server?

 I notice this message is present in 
drupal.api.js:194 (xhr)

```
    error: (function(api) {
      return function(xhr, ajaxOptions, thrownError) {
        api.loading(false);
        console.log(xhr.statusText);
        if (callback) {
          callback(null);
        }
```

**Comment by travist** [comment]
It is currently an unhandled exception.  You can handle it yourself by wrapping the save in a `try { } catch(e) {}` block like so.

``` javascript
try {
  (new drupal.node({title:"",type:"page"})).save(function(node) {
    console.log(node);
    //console.log(xhr.statusText);
  });
} 
catch(err) {
  // Do something...
  console.log(err.message);
}

```

**Comment by giorgio79** [comment]
Thx, just tried, but catch is never reached. 

The Drupal message on failed node submission is inside xhr.responseText, inside the formErrors array. Would be great to expose that :) I am looking at this solution as well https://github.com/jbeuckm/drupal-client Seems it has some error management.
